In [30]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('../临时文件/9-28-10-12用户付费.csv',index_col=False)[['用户App登录ID','首次安装App时间','事件发生时间','Total']]

In [7]:
df['install_time']= pd.to_datetime(df['首次安装App时间'])
df['ng_time']=pd.to_datetime(df['事件发生时间'],unit='ms')

In [9]:
# 计算内购时生命周期天数
df['live_day'] = (df['ng_time'] - df['install_time']).dt.days

In [19]:
# 分组
df['cuts'] = pd.cut(
    df['live_day'],# 需要分组的列
    bins=[0,7,14,21,1000],# 分组的组数或者自定义分组列表
    labels=['第一周','第二周','第三周','第四周'],
    right=False,# 是否包含右边的值
    include_lowest=True # 是否包含最低值
    
)

In [31]:
df['第一周付费用户'] = df.apply(lambda x:1 if x['cuts']=='第一周' else 0 ,axis=1)
df['前二周付费用户'] = df.apply(lambda x:1 if x['cuts'] in ['第一周','第二周'] else 0 ,axis=1)
df['前三周付费用户'] = df.apply(lambda x:1 if x['cuts']in ['第一周','第二周','第三周']  else 0 ,axis=1)
df['前四周付费用户'] = df.apply(lambda x:1 if x['cuts']in ['第一周','第二周','第三周','第四周']  else 0 ,axis=1)

In [39]:
# 不同分组的用户金额分布
df1=df.query('第一周付费用户==1').groupby(by='用户App登录ID',as_index=False)['Total'].sum()
df1['区间']=pd.cut(
    df1['Total'],
    bins=[0,20,40,60,80,100,100000],# 分组的组数或者自定义分组列表
    labels=['0-20','20-40','40-60','60-80','80-100','100+'],
    right=False,# 是否包含右边的值
    include_lowest=True # 是否包含最低值
)
# 不同区间的人数
df1=df1.groupby(by='区间',as_index=False)[['用户App登录ID','Total']].agg({
    '用户App登录ID':'nunique',
    'Total':'sum'
})

In [40]:
df1

       区间  用户App登录ID  Total
0    0-20        533   2790
1   20-40        105   2900
2   40-60         54   2664
3   60-80         36   2410
4  80-100         21   1814
5    100+         37   6967

In [41]:
df2=df.query('前二周付费用户==1').groupby(by='用户App登录ID',as_index=False)['Total'].sum()
df2['区间']=pd.cut(
    df2['Total'],
    bins=[0,20,40,60,80,100,100000],# 分组的组数或者自定义分组列表
    labels=['0-20','20-40','40-60','60-80','80-100','100+'],
    right=False,# 是否包含右边的值
    include_lowest=True # 是否包含最低值
)
# 不同区间的人数
df2=df2.groupby(by='区间',as_index=False)[['用户App登录ID','Total']].agg({
    '用户App登录ID':'nunique',
    'Total':'sum'
})

In [42]:
df2

       区间  用户App登录ID  Total
0    0-20        526   2697
1   20-40        108   2920
2   40-60         62   3098
3   60-80         42   2874
4  80-100         30   2678
5    100+         58  12228

In [43]:
df3=df.query('前三周付费用户==1').groupby(by='用户App登录ID',as_index=False)['Total'].sum()
df3['区间']=pd.cut(
    df3['Total'],
    bins=[0,20,40,60,80,100,100000],# 分组的组数或者自定义分组列表
    labels=['0-20','20-40','40-60','60-80','80-100','100+'],
    right=False,# 是否包含右边的值
    include_lowest=True # 是否包含最低值
)
# 不同区间的人数
df3=df3.groupby(by='区间',as_index=False)[['用户App登录ID','Total']].agg({
    '用户App登录ID':'nunique',
    'Total':'sum'
})

In [44]:
df3

       区间  用户App登录ID  Total
0    0-20        519   2695
1   20-40        109   2952
2   40-60         62   3127
3   60-80         36   2428
4  80-100         36   3185
5    100+         74  15604