In [1]:
import datetime
import sys
# path为tools的上层文件夹
sys.path.append('D:\milimili')
import numpy as np
import pandas as pd
from configs import TE_app_token
from tools.数数查询 import get_sqldata
token=TE_app_token['Doomsday Vanguard']

In [2]:
# -- 玩家英雄获取
sql1="""
select "name","quality","#account_id","#event_time"
FROM 
 ta.v_event_33 
where "$part_event"= 'role_get'
and  "$part_date" between '2023-12-01' and '2024-03-11'
"""


# ---- 玩家英雄上场数据
sql2 = """
SELECT "#account_id","#event_time","level_role"
FROM  
 ta.v_event_33 
where "$part_event" = 'Game_Level_Finish'
 and  "$part_date" between '2023-12-01' and '2024-03-11'
"""

In [3]:
df_role_get=get_sqldata(token,sql1)

In [6]:
df_role_get.columns=['角色名称','角色等级','玩家id','获取时间']

In [7]:
df_role_fight=get_sqldata(token,sql2)

In [10]:
df_role_fight.columns=['玩家id','战斗时间','角色名称']

In [11]:
# 统计角色获取情况
df_role = df_role_get.groupby(by=['角色名称','角色等级'],as_index=False)['玩家id'].nunique()

In [14]:
df_role=df_role.query('角色名称!="null"')

In [15]:
df_role

          角色名称 角色等级    玩家id
0        Alice    5   72378
1       Angela    5    1093
2       Baobao    3  198646
3    Blueberry    4  133474
4         Burn    4  133745
5       Camila    4  137917
6      Chiharu    5   23161
7        Coola    5   22664
8         Eric    4  133617
9       Kanade    5    2035
10      Kanoka    5   22637
11       Kasha    5    4171
12        Kate    3  365967
13        Kira    3  198544
14        Lena    5    5719
15         Ley    4  133641
16        Lian    5     396
17        Luna    5     445
18        Meow    5    3318
19         Mio    4  133168
20        Misa    5    1407
21      Miyako    3     346
22        Momo    5     689
23      Monroe    5   22750
24      Morgan    5   23749
25        Niko    5   22545
26       Snake    5    6894
27       Sonar    3  198979
28       Taito    5   22481
29       Thorn    5   23233
30        Toph    4  133396
31       Vepar    5     158
32      Verena    4  132648
33  Watermelon    5   21310
34        Yoyo    3  198533

In [16]:
# 玩家获取角色后该角色出场次数
role_fight=df_role_fight.groupby(by='角色名称',as_index=False)['玩家id'].count()

In [17]:
role_fight

          角色名称     玩家id
0        Alice  1144496
1       Angela    24983
2       Baobao   174383
3    Blueberry   289893
4         Burn   334658
5       Camila   721023
6      Chiharu   221941
7        Coola   280923
8         Eric   321659
9       Kanade    31842
10      Kanoka   218924
11       Kasha    64160
12        Kate  1121732
13        Kira   108754
14        Lena    67903
15         Ley   270175
16        Lian     9748
17        Luna    10975
18        Meow    87168
19         Mio   321542
20        Misa    25285
21      Miyako   859067
22        Momo    17796
23      Monroe   186726
24      Morgan   504091
25        Niko   203146
26       Snake    56503
27       Sonar   122026
28       Taito   269323
29       Thorn   253727
30        Toph   497033
31       Vepar     2717
32      Verena   559495
33  Watermelon   192482
34        Yoyo   222857

In [19]:
# 玩家获取某英雄后，其他英雄的获取个数
df_role_get.head(20)

,角色名称,角色等级,玩家id,获取时间
0,Kira,3,4c760052-13f0-4015-8792-a3f7f546cbd1,2024-03-11 23:20:38.176
1,Sonar,3,8583a51d-f76b-44e0-8331-ab3f72d215e5,2024-03-11 21:48:52.021
2,Toph,4,eb86243b-f8d0-469b-873e-52aa311d4c06,2024-03-11 21:48:30.242
3,Blueberry,4,4c760052-13f0-4015-8792-a3f7f546cbd1,2024-03-11 23:20:12.381
4,Yoyo,3,aa7afb2d-dfbf-4fac-86d4-ff5f65b8880b,2024-03-06 15:02:02.891
5,Kate,3,0ddf04b3-c02a-4e87-8396-fac47ec25452,2024-01-30 02:29:33.102
6,Burn,4,c243a10f-a9ee-4d03-bcb8-42f38ce7dd22,2024-01-30 02:32:45.656
7,Baobao,3,87deb459-7f07-4f03-8b57-0b5900341cdc,2024-01-30 04:59:07.688
8,Burn,4,58e33729-aea8-42cd-9fdc-288e032482a5,2024-01-30 03:07:19.841
9,Sonar,3,6275788b-2a72-4317-b72d-8b166ec9d5a5,2024-01-30 00:19:12.814
10,Kate,3,5e6954c4-0fdf-4d5e-899a-8dba2f60dae7,2024-01-30 00:25:22.367
11,Verena,4,9f71fdd3-2bf6-416e-bdd5-bdc27340a060,2024-01-30 06:43:36.126
12,Sonar,3,0fcbc766-31d4-4080-9fa0-2a99bdd3e120,2024-01-30 05:48:24.947
13,Yoyo,3,863554af-49ee-4963-aec3-6b72d03e6c6e,2024-01-30 06:56:47.974
14,Toph,4,0c32e3ab-ea00-4543-93cf-1522992bcc1c,2024-01-30 04:05:17.232
15,Kate,3,343d51b0-d68a-4d19-8fc9-3c5cf3d2fb0f,2024-01-30 04:14:28.684
16,Ley,4,9923a072-c659-4167-8965-9dbaab3006a3,2024-01-30 04:15:10.913
17,Kate,3,18f00d44-1db2-4e94-81d1-aac8245a84c2,2024-01-30 04:20:45.085
18,Niko,5,35eeaa65-b946-4072-8bbf-4db1b7e0b088,2024-01-30 04:27:21.039
19,Morgan,5,6d3ae349-d27d-4729-893b-1eaa7cc32817,2024-01-30 03:31:16.182

In [20]:
df_role_geting = df_role_get.sort_values(by=['玩家id','获取时间'],ascending=[True,True])

In [23]:
df_role_geting['获取该角色后获取角色数量']=df_role_geting.groupby(by='玩家id')['获取时间'].rank(ascending=False,method='dense')

In [25]:
df_role_geting=df_role_geting.query('玩家id==玩家id')

In [27]:
df_role_geting['获取该角色后获取角色数量']=df_role_geting['获取该角色后获取角色数量']-1

C:\Users\admin\AppData\Local\Temp\ipykernel_13492\2456748761.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_role_geting['获取该角色后获取角色数量']=df_role_geting['获取该角色后获取角色数量']-1

In [28]:
df_role_geting

,角色名称,角色等级,玩家id,获取时间,获取该角色后获取角色数量
2478768,Kate,3,00004cfa-5328-4ba4-8cea-3c8f2a692ec9,2024-02-02 15:52:24.913,12.0
2477911,Sonar,3,00004cfa-5328-4ba4-8cea-3c8f2a692ec9,2024-02-02 16:06:13.196,11.0
1929266,Blueberry,4,00004cfa-5328-4ba4-8cea-3c8f2a692ec9,2024-02-02 16:09:21.173,10.0
2478450,Alice,5,00004cfa-5328-4ba4-8cea-3c8f2a692ec9,2024-02-02 16:21:26.709,9.0
2478197,Baobao,3,00004cfa-5328-4ba4-8cea-3c8f2a692ec9,2024-02-02 16:21:50.478,8.0
...,...,...,...,...,...
700410,Blueberry,4,ffffe274-839d-47c3-84d0-ab3b8008a47b,2024-01-06 11:47:34.781,0.0
2429125,Kate,3,fffff341-ba57-4279-a252-19acc61dc51f,2024-02-23 21:35:05.590,3.0
1744029,Ley,4,fffff341-ba57-4279-a252-19acc61dc51f,2024-02-25 14:40:21.615,2.0
1744636,Sonar,3,fffff341-ba57-4279-a252-19acc61dc51f,2024-02-25 14:40:27.752,1.0
1744748,Eric,4,fffff341-ba57-4279-a252-19acc61dc51f,2024-02-25 14:40:33.999,0.0

In [31]:
df_role_orther_get = df_role_geting.groupby(by='角色名称',as_index=False)[['玩家id','获取该角色后获取角色数量']].agg({
    '玩家id':'nunique',
    '获取该角色后获取角色数量':'sum'
}).query('角色名称!="null"')

In [32]:
df_role_orther_get

          角色名称    玩家id  获取该角色后获取角色数量
0        Alice   72378      476920.0
1       Angela    1093        4143.0
2       Baobao  198646     1147095.0
3    Blueberry  133474      653033.0
4         Burn  133745      651344.0
5       Camila  137917      692400.0
6      Chiharu   23161       65370.0
7        Coola   22664       63242.0
8         Eric  133617      651034.0
9       Kanade    2035        6531.0
10      Kanoka   22637       61757.0
11       Kasha    4171       12648.0
12        Kate  365967     2049597.0
13        Kira  198544     1149180.0
14        Lena    5719       14320.0
15         Ley  133641      655189.0
16        Lian     396         633.0
17        Luna     445        1634.0
18        Meow    3318        7954.0
19         Mio  133168      652169.0
20        Misa    1407        5749.0
21      Miyako     346        1442.0
22        Momo     689        2047.0
23      Monroe   22750       63279.0
24      Morgan   23749       70591.0
25        Niko   22545       62786.0
26       Snake    6894        7187.0
27       Sonar  198979     1148209.0
28       Taito   22481       62503.0
29       Thorn   23233       66670.0
30        Toph  133396      654385.0
31       Vepar     158         709.0
32      Verena  132648      654167.0
33  Watermelon   21310       58207.0
34        Yoyo  198533     1149700.0

In [33]:
# 玩家连续抽卡情况

In [47]:
# 钻石卡池
sql3 = """
select "#account_id","#event_time",
case when "$part_date" between '2023-12-06' and '2023-12-24' then '奏'
     when "$part_date" between '2023-12-25' and '2024-01-14' then '卡莎' 
     when "$part_date" between '2024-01-15' and '2024-02-12' then '蕾娜'
     when "$part_date" between '2024-02-13' and '2024-03-11' then '银蛇'
end as "role_name"
from  
ta.v_event_33 
where "$part_event" = 'Activity_recruit'
and "$part_date" between '2023-12-01' and '2024-03-11'
and "type" = '23'
"""

# 盲盒卡池
sql4= """
select "#account_id","#event_time",
case when "$part_date" between '2023-12-11' and '2023-12-31' then '维帕尔'
     when "$part_date" between '2024-01-01' and '2024-01-28' then '月' 
     when "$part_date" between '2024-01-29' and '2024-02-25' then '桃子'
     when "$part_date" between '2024-02-26' and '2024-03-11' then '莲'
end as "role_name"
from  
ta.v_event_33 
where "$part_event" = 'Activity_recruit'
and "$part_date" between '2023-12-01' and '2024-03-11'
and "type" = '22'
"""

In [48]:
role_get_zuanshi = get_sqldata(token,sql3)

In [52]:
role_get_zuanshi.columns=['玩家id','抽卡时间','卡池角色']

In [39]:
role_get_manghe = get_sqldata(token,sql4)

In [53]:
role_get_manghe.columns=['玩家id','抽卡时间','卡池角色']

In [66]:
# 连续参与漏斗
role_get_zuanshi['奏']=role_get_zuanshi.apply(lambda x: 1 if x['卡池角色']=='奏' else 0,axis=1)
role_get_zuanshi['卡莎']=role_get_zuanshi.apply(lambda x: 1 if x['卡池角色']=='卡莎' else 0,axis=1)
role_get_zuanshi['蕾娜']=role_get_zuanshi.apply(lambda x: 1 if x['卡池角色']=='蕾娜' else 0,axis=1)
role_get_zuanshi['银蛇']=role_get_zuanshi.apply(lambda x: 1 if x['卡池角色']=='银蛇' else 0,axis=1)

In [83]:
# 抽卡参与人数
role_get_zuanshi.groupby(by='卡池角色',as_index=False)['玩家id'].nunique()

   卡池角色   玩家id
0  null     11
1    卡莎  21439
2     奏  13615
3    蕾娜  24422
4    银蛇  30835

In [67]:
role_get_manghe['维帕尔']=role_get_manghe.apply(lambda x: 1 if x['卡池角色']=='维帕尔' else 0,axis=1)
role_get_manghe['月']=role_get_manghe.apply(lambda x: 1 if x['卡池角色']=='月' else 0,axis=1)
role_get_manghe['桃子']=role_get_manghe.apply(lambda x: 1 if x['卡池角色']=='桃子' else 0,axis=1)
role_get_manghe['莲']=role_get_manghe.apply(lambda x: 1 if x['卡池角色']=='莲' else 0,axis=1)

In [85]:
role_get_manghe.groupby(by='卡池角色',as_index=False)['玩家id'].nunique()

   卡池角色  玩家id
0  null     1
1     月  1044
2    桃子  1329
3   维帕尔   361
4     莲   731

In [70]:
df1=role_get_zuanshi.groupby(by='玩家id',as_index=False)[['奏','卡莎','蕾娜','银蛇']].agg({
    '奏':'sum',
    '卡莎':'sum',
    '蕾娜':'sum',
    '银蛇':'sum'
})

In [76]:
df2=role_get_manghe.groupby(by='玩家id',as_index=False)[['维帕尔','月','桃子','莲']].agg({
    '维帕尔':'sum',
    '月':'sum',
    '桃子':'sum',
    '莲':'sum'
})

In [71]:
# 参与奏抽卡人数
zou  = df1.query('奏>0')['玩家id'].nunique()
# 参与奏和卡莎 抽卡人数
zou_kasha =  df1.query('奏>0&卡莎>0')['玩家id'].nunique()
# 参与奏、卡莎、蕾娜抽卡人数
zou_kasha_leina = df1.query('奏>0&卡莎>0&蕾娜>0')['玩家id'].nunique()
#全部抽卡参与人数
role_all = df1.query('奏>0&卡莎>0&蕾娜>0&银蛇>0')['玩家id'].nunique()

In [88]:
#卡莎蕾娜
df1.query('蕾娜>0&银蛇>0')['玩家id'].nunique()

9390

In [78]:
# 参与为帕尔抽卡人数
wpe  = df2.query('维帕尔>0')['玩家id'].nunique()
# 参与为帕尔和月抽卡人数
wpe_yue =  df2.query('维帕尔>0&月>0')['玩家id'].nunique()
# 参与前三个抽卡人数
wpe_yue_tz = df2.query('维帕尔>0&月>0&桃子>0')['玩家id'].nunique()
#全部抽卡参与人数
mhrole_all = df2.query('维帕尔>0&月>0&桃子>0&莲>0')['玩家id'].nunique()

In [91]:
df2.query('桃子>0&莲>0')['玩家id'].nunique()

211

In [72]:
zou

13615

In [73]:
zou_kasha

5279

In [74]:
zou_kasha_leina

2181

In [75]:
role_all

1003

In [79]:
wpe

361

In [80]:
wpe_yue

86

In [81]:
wpe_yue_tz

26

In [82]:
mhrole_all

10